### ISSUE TITLE
Start with forge

### ISSUE THREAD

**Issue by brutalzinn** [AlphaBs/MinecraftLauncherLibrary#1]
How do I start minecraft with forge? the wiki is offline.

**Comment by AlphaBs** [comment]
sorry i don't have time to write wiki

Forge launch source contains sample project. build CmlLibSample project and test launch.
[goto source code](https://github.com/AlphaBs/MinecraftLauncherLibrary/blob/master/CmlLibSample/Form1.cs)
(see 145~194 lines)

**Comment by brutalzinn** [comment]
I'm a problem. is giving session problem. But before it was working perfectly.

**Comment by brutalzinn** [comment]
Session is null

**Comment by brutalzinn** [comment]
if (Sanchez.Patcher.Properties.Settings.Default.Conta == true)
            {

                MLogin login = new MLogin();



                session = login.Authenticate(
                     textBox1.Text,
                     textBox2.Text);


           


            }
            else
            {

                MSession session = MSession.GetOfflineSession(textBox3.Text);

            }

**Comment by AlphaBs** [comment]
did you check login result? if session.Result isn't MLoginResult.Success, you will be returned null by  session.AccessToken, Username, UUID.

did you try a CmlLibSample? if you failed login in sample launcher, could you give me your full source code? (ksi123456ab@naver.com)

many user use my launcher, but i have never seem that error

**Comment by brutalzinn** [comment]
I was able to solve the problem. If you can help me in the other ... :)

I used Google Translator.
