### ISSUE TITLE
1.15.2 doesn't supported!

### ISSUE THREAD

**Issue by karlovm** [AlphaBs/MinecraftLauncherLibrary#10]
I tried to use 1.15.2 minecraft version and had nothing. Console starts and after a moment closes.

**Comment by AlphaBs** [comment]
can you show me your code?

**Comment by karlovm** [comment]
`using CmlLib.Launcher;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using MessageBox = System.Windows.Forms.MessageBox;

namespace PolitEarth
{
    /// <summary>
    /// Логика взаимодействия для MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            String Pat = Environment.GetEnvironmentVariable("appdata") + "\\.minecraft";
            Minecraft.Initialize(Pat);
            usen.Text = Properties.Settings.Default.username;
        }
        string appData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
        string Directory = ".minecraftplus", login, way, waylib, url, file, dir;
        private string GetJavaInstallationPath()
        {
            string environmentPath = Environment.GetEnvironmentVariable("JAVA_HOME");
            if (!string.IsNullOrEmpty(environmentPath))
            {
                return environmentPath;
            }

            string javaKey = "SOFTWARE\\JavaSoft\\Java Runtime Environment\\";
            using (Microsoft.Win32.RegistryKey rk = Microsoft.Win32.Registry.LocalMachine.OpenSubKey(javaKey))
            {
                string currentVersion = rk.GetValue("CurrentVersion").ToString();
                using (Microsoft.Win32.RegistryKey key = rk.OpenSubKey(currentVersion))
                {
                    return key.GetValue("JavaHome").ToString();
                }
            }
        }
        MProfileInfo[] infos = null;
        private void Button_Click(object sender, RoutedEventArgs e)
        {
            
            try
            {
                // MessageBox.Show(GetJavaInstallationPath());
                MSession session;
                if (usen.Text != "")
                {
                    session = MSession.GetOfflineSession(usen.Text);
                }
                else
                {
                    MessageBox.Show("Введите никнейм");
                    return;
                }



                Properties.Settings.Default.username = usen.Text;
                Properties.Settings.Default.Save();

                var th = new Thread(new ThreadStart(delegate
                {
                    try { 

                    infos = MProfileInfo.GetProfiles();
                    var profile = MProfile.FindProfile(infos, "1.15.1"); // Find Profile

                MDownloader downloader = new MDownloader(profile);
                //    downloader.ChangeFile += change_file;
                //   downloader.ChangeProgress += change_progress;
                downloader.DownloadAll(); // Download game files
                        String ip = "";
                        if(Properties.Settings.Default.loginonstart)
                        {
                            ip = "politmine.ru";
                        }
                MLaunchOption option = new MLaunchOption() // Set options
                {
                        StartProfile = profile,
                        JavaPath = "java.exe", //SET YOUR JAVA PATH (if you want autoset, goto wiki)
                    MaximumRamMb = Properties.Settings.Default.mem, // MB

                    Session = session,
                        LauncherName = "PolitEarth",

                       ScreenHeight = Properties.Settings.Default.height,
                       ScreenWidth = Properties.Settings.Default.width,

                        ServerIp = ip,

                        


                    };

                        

                    MLaunch launch = new MLaunch(option); // Start Process
                var process = launch.GetProcess();
                    process2 = process;
                    Thread a = new Thread(DebugProcess);
                    a.Start();
                     
                    }
            catch (Exception ea)
            {
                        System.Windows.Application.Current.Dispatcher.Invoke(new Action(() => {
                            Show(); Topmost = true; Topmost = false;
                            Show();
                            Window1 a = new Window1(errotr + "\n" + ea.Message);
                        
                        }));
               
            }

        }));
                th.Start();
            }
            catch(Exception ea)
            {
                Show();
                Window1 a = new Window1(errotr + "\n" + ea.Message);
                
            }
        }



        #region DEBUG PROCESS
        Process process2 = null;
        private void DebugProcess()
        {
            // Console.WriteLine("Write game args");
            //    File.WriteAllText("launcher.txt", process.StartInfo.Arguments);

            //    Console.WriteLine("Set Debug Process");

            Process process = process2; process.EnableRaisingEvents = true;
            process.StartInfo.UseShellExecute = false;
            process.Exited += closed;
            if (Properties.Settings.Default.consolehide)
            {
                process.StartInfo.CreateNoWindow = true;
           
                process.StartInfo.RedirectStandardError = true;
                process.StartInfo.RedirectStandardOutput = true;

                process.ErrorDataReceived += Process_ErrorDataReceived;
                process.OutputDataReceived += Process_OutputDataReceived;
             
            }
            process.Start();
            process.BeginErrorReadLine();
            process.BeginOutputReadLine();
            System.Windows.Application.Current.Dispatcher.Invoke(new Action(() => { Hide(); }));


            //   Console.WriteLine("Start Debug Process");

            if (!Properties.Settings.Default.consolehide)
            {
                Close();
            }
            }
        
        private void Button_Click_1(object sender, RoutedEventArgs e)
        {
            settings s = new settings();
            s.Show();
        }

        Boolean error = false;
        String errotr = "";
        private void closed(object sender, EventArgs e)
        {
            System.Windows.Application.Current.Dispatcher.Invoke(new Action(() => { Show(); Topmost = true; Topmost = false; 
            if(error)
                {
                    Window1 a = new Window1(errotr);
                   
                }
            }));
        }

        private void Process_OutputDataReceived(object sender, DataReceivedEventArgs e)
        {
            output(e.Data);

        }

        private void Process_ErrorDataReceived(object sender, DataReceivedEventArgs e)
        {
            output(e.Data);
            error = true;
            errotr = errotr + "\n" + e.Data;

        }

        void output(string msg)
        {
            msg += "\n";
            Console.WriteLine(msg);
        }

        #endregion

      
    }
}
`

**Comment by karlovm** [comment]
There is a lot of trash code, but if it can be a problem I give you all my class.

**Comment by karlovm** [comment]
I can say more: your example can't start that version too. There are no problems with OptiFine 1.14 but "OptiFine 1.15.2" and "1.15.2" doesn't work. And about threads:  i will insert them in future.

**Comment by AlphaBs** [comment]
I tested 1.15.2 but it works well
and I made new sample launcher which show game logs, so use this  [SampleLauncher](https://github.com/AlphaBs/MinecraftLauncherLibrary/releases/download/1.0.1/SampleLauncher.zip) and please show your game logs

**Comment by karlovm** [comment]
[15:56:20] [main/INFO]: Loading tweak class name net.minecraft.launchwrapper.VanillaTweaker
[15:56:20] [main/ERROR]: Unable to launch

java.lang.ClassNotFoundException: net.minecraft.launchwrapper.VanillaTweaker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:102) ~[launchwrapper-of-2.1.jar:2.1]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_51]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:122) [launchwrapper-of-2.1.jar:2.1]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.1.jar:2.1]

**Comment by karlovm** [comment]
it is 1.15.2 without optifine^
Exception in thread "main" joptsimple.MissingRequiredOptionsException: Missing required option(s) [accessToken, version]
	at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:426)

	at joptsimple.OptionParser.parse(OptionParser.java:400)
	at net.minecraft.client.main.Main.main(SourceFile:75)

**Comment by ilsubyeega** [comment]
> it is 1.15.2 without optifine^
> Exception in thread "main" joptsimple.MissingRequiredOptionsException: Missing required option(s) [accessToken, version]
> at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:426)
> 
> ```
> at joptsimple.OptionParser.parse(OptionParser.java:400)
> at net.minecraft.client.main.Main.main(SourceFile:75)
> ```

That is optifine feature.
Currently optifine don't support 1.15 Forge.

**Comment by ilsubyeega** [comment]
@etysoftware can you try at minecraft official launcher?

**Comment by karlovm** [comment]
I don't have license. But TLauncher minecraft works perfect (1.15.2, 1.15.2 with optifine)

**Comment by AlphaBs** [comment]
I can't reproduce your error.

Delete %appdata%/.minecraft/runtime and versions directory and retry to launch through SampleLauncher

If you get a same error again, please send your project and .minecraft folder to ksi123456ab@naver.com

**Comment by ilsubyeega** [comment]
I did with SampleLauncher with offline mode, it works.
I really think tlauncher probably doing something wrong
as AlphaBs's saying, try that.

**Comment by karlovm** [comment]
I have deleted 1.15.2 dir and download it manually via your library. And it works! But i think tlauncher can do wrong thing in future. And a little question: when OptiFine 1.15.2? Wait for custom minecraft icon:)

**Comment by AlphaBs** [comment]
1.15.2 optifine is not released now. Where did you download it?

**Comment by karlovm** [comment]
OptiFine site, preview Versions

**Comment by ilsubyeega** [comment]
> When OptiFine 1.15.2?

from optifine changelogs, currently 1.15.2 optifine is not compatible with Forge.

**Comment by karlovm** [comment]
I'm not going to use optifine with Forge

**Comment by ilsubyeega** [comment]
(Wrong Comment)

**Comment by AlphaBs** [comment]
1.1.0 released. now CmlLib supports 1.15.2 optifine and is compatible with TLauncher. (but CmlLib is not stable with TLauncher)
