### ISSUE TITLE
How can I change the icon of minecraft?

### ISSUE THREAD

**Issue by karlovm** [AlphaBs/MinecraftLauncherLibrary#11]
I can't find in wiki how I can change the icon of Minecraft. I know that it is possible.

**Comment by AlphaBs** [comment]
CmlLib doesn't support such function now. but i will add it

**Comment by karlovm** [comment]
Wait for it

**Comment by AlphaBs** [comment]
I added `-Xdock:icon` argument but It works only in macOS. In windows, I think there is no option that can change default icon(craft table) to what i want. How did you know it?

**Comment by ilsubyeega** [comment]
I saw some sources and i couldn't find that when initialized.
by the way, you can change the icon on `com.mojang.blaze3d.platform.Window` with `setIcon(InputStream input2, InputStream input2)` (not available with csharp)

**Comment by karlovm** [comment]
Search for "sashok launcher". His launcher supports icon change

**Comment by karlovm** [comment]
And i heard that it is opensource

**Comment by ilsubyeega** [comment]
> sashok launche

They [override the class](https://github.com/new-sashok724/Launcher/blob/ae9bab65a8d0a571261fec84a62752217ac5c378/Launcher/runtime/init.js#L11).
Im not sure it could be dangerous

**Comment by karlovm** [comment]
Try it!

**Comment by ilsubyeega** [comment]
I cannot find the [library in java](https://docs.oracle.com/javase/8/docs/api/javax/script/ScriptEngine.html).
use that if you actually want it. idk about that solution

**Comment by AlphaBs** [comment]
It's impossible in C#. you have to make java program which set program icon and run java class.
