### ISSUE TITLE
How to run optifine 1.15.2?

### ISSUE THREAD

**Issue by karlovm** [AlphaBs/MinecraftLauncherLibrary#15]
I try in different ways to launch minecraft with OptiFine version 1.15.2 without the support of forge, but all this was unsuccessful.Please explain how to do this.

**Comment by karlovm** [comment]
I download optifine, select "Install" and try to start optifine version. I can do it with Tlauncher, but can't with your library. Maybe something what i do is wrong?

**Comment by AlphaBs** [comment]
I can launch optifine very well. remove versions directory and reinstall optifine.
and don't run TLauncher. TLauncher makes profile incompatible with Mojang launcher and CmlLib.
