### ISSUE TITLE
Minecraft with lag and crashes

### ISSUE THREAD

**Issue by brutalzinn** [AlphaBs/MinecraftLauncherLibrary#2]
Hello. My minecraft opens with the forge, all right. But you can not play. It's very slow. Issó occurs in my project, in the sample provided by you (sometimes works) in the other launchers my client works perfectly. What can it be?

THANKFUL
I love this libray.

**Comment by brutalzinn** [comment]
my code is here: `using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Windows.Forms;

using System.IO;
using CmlLib.Launcher;
using Sanchez.Patcher.Source_files;
using System.Threading;

namespace Sanchez.Patcher.Forms
{
    public partial class launcher : Form
    {
        public launcher()
        {
            InitializeComponent();
            Globals.Launcher = this;
            bool iswindowmode = false;


        }
        MProfileInfo[] versions;
        MSession session;
   MProfile profile = null;

        private void button1_Click(object sender, EventArgs e)
        {

        

         

            if (File.Exists(Sanchez.Patcher.Properties.Settings.Default.javapath)) {
            
               

                session = MSession.GetOfflineSession(textBox3.Text);






                string nn = Globals.versãodominecraft;
            string jj = Sanchez.Patcher.Properties.Settings.Default.javapath;

                string ln = "";
            string server = Globals.ipdoserver;

            var th = new Thread(new ThreadStart(delegate
            {



               
                MProfile forgeProfile = null;

                foreach (var item in versions)
                {
                    if (item.Name == nn)
                    {
                        profile = MProfile.Parse(item);
                        break;
                    }
                }

                if (profile.IsForge)
                {
                    foreach (var item in versions)
                    {
                        if (item.Name == profile.InnerJarId)
                        {
                            forgeProfile = MProfile.Parse(item);
                            break;
                        }
                    }

                    DownloadGame(forgeProfile, true);
                }

                DownloadGame(profile, !profile.IsForge);

                MLaunchOption option = new MLaunchOption()
                {
                    BaseProfile = forgeProfile,
                    StartProfile = profile,
                    JavaPath = jj,
                    LauncherName = ln,
                    MaximumRamMb = 500,// Sanchez.Patcher.Properties.Settings.Default.memoria,
                    ServerIp = server,
                    Session = session,
                    CustomJavaParameter = Sanchez.Patcher.Properties.Settings.Default.javaargument
                };

                if (Sanchez.Patcher.Properties.Settings.Default.largura != "" && Sanchez.Patcher.Properties.Settings.Default.altura != "")
                {
                    option.ScreenHeight = int.Parse(Sanchez.Patcher.Properties.Settings.Default.altura);
                    option.ScreenWidth = int.Parse(Sanchez.Patcher.Properties.Settings.Default.largura);
                }

                MLaunch launch = new MLaunch(option);
                var pro = launch.GetProcess(); // 인수 생성 후 설정된 Process 객체 가져옴
                System.IO.File.WriteAllText("mcarg.txt", pro.StartInfo.Arguments); // 만들어진 인수 파일로 저장 (디버그용)
                pro.Start(); // Process 객체로 실행

                this.Invoke((MethodInvoker)delegate
                {

                });
            }));
            th.Start();





            }
            else
            {

                timer1.Enabled = false;
                MessageBox.Show("Diretório java não encontrado. Por favor configure-o corretamente.  Está com dúvidas? \r\n consulte a equipe do survivalcrafters. ");


            }


        }

        private void usoDaMemóriaToolStripMenuItem_Click(object sender, EventArgs e)
        {

        }

        private void editorDeMemóriaToolStripMenuItem_Click(object sender, EventArgs e)
        {



            Patcher.Forms.configurarmemoria f2 = new Patcher.Forms.configurarmemoria();
            f2.ShowDialog();
        }

        private void nomeToolStripMenuItem_Click(object sender, EventArgs e)
        {
            //   Patcher.Forms.editordeconta f2 = new Patcher.Forms.editordeconta();
            //  f2.ShowDialog();
        }

        private void Launcher_Load(object sender, EventArgs e)
        {


            MSession session = null;


            //            Txt_Java.Text = Minecraft.mPath + "\\runtime\\bin\\javaw.exe";
        }

        private void tipoDeContaToolStripMenuItem_Click(object sender, EventArgs e)
        {

        }

        private void mudarTipoDeContaToolStripMenuItem_Click(object sender, EventArgs e)
        {
            Patcher.Forms.Formulario f2 = new Patcher.Forms.Formulario();
            f2.ShowDialog();
        }
    
        private void Launcher_Shown(object sender, EventArgs e)
        {
            Minecraft.init(Sanchez.Patcher.Properties.Settings.Default.minecraftlocal);


            versions = MProfileInfo.GetProfiles();
            Invoke((MethodInvoker)delegate
            {
                foreach (var item in versions)
                {
                    comboBox1.Items.Add(item.Name);
                }
            });
            webBrowser1.Url = new Uri( Globals.sitedobrowser);

       //     label5.Text = Sanchez.Patcher.Properties.Settings.Default.Conta.ToString();
           // string minecraft = Environment.GetEnvironmentVariable("appdata") + "\\survivalcrafters";
      //
          //  Sanchez.Patcher.Properties.Settings.Default.minecraftlocal = minecraft;
          //  Sanchez.Patcher.Properties.Settings.Default.Save();


       //     label5.Text = minecraft;

            versions = MProfileInfo.GetProfiles();



            var th = new Thread(new ThreadStart(delegate
            {
              

                versions = MProfileInfo.GetProfiles();
                //      Invoke((MethodInvoker)delegate
                //      {
                //   foreach (var item in versions)
                {
                    //       //       //Cb_Version.Items.Add(item.Name);
                    //          }
                    //      });
                    if (checkBox2.Checked == true)
                    {





                        var login = new MLogin();
                        MSession result = login.TryAutoLogin();

                        if (result.Result != MLoginResult.Success)
                            return;

                        MessageBox.Show("Auto Login foi um sucesso!");
                        session = result;
                    }
                    Invoke((MethodInvoker)delegate { button1.Enabled = true; });
                } }));
            th.Start();

   //         Minecraft.init(Environment.GetEnvironmentVariable("appdata") + "\\.minecraft");
            checkBox1.Checked = Sanchez.Patcher.Properties.Settings.Default.windowmode;
            checkBox2.Checked = Sanchez.Patcher.Properties.Settings.Default.passwordsave;

            if (checkBox2.Checked == true)
            {
                //   textBox1.Text = Sanchez.Patcher.Properties.Settings.Default.email;
                //   textBox2.Text = Sanchez.Patcher.Properties.Settings.Default.senha;
                Console.WriteLine("chegoou aqui");

            }






            timer1.Enabled = true;



            // Sanchez.Patcher.Properties.Settings.Default.email = "";
            //   Sanchez.Patcher.Properties.Settings.Default.senha = "";



            if (Sanchez.Patcher.Properties.Settings.Default.Conta == false)
            {

                groupBox1.Visible = false;
                groupBox2.Visible = true;
                nomeToolStripMenuItem.Visible = true;
                textBox3.Text = Sanchez.Patcher.Properties.Settings.Default.nickname;
                // label4.Text = "Usuário crackeado";

            }
            else
            {
                groupBox2.Visible = false;
                groupBox1.Visible = true;
                nomeToolStripMenuItem.Visible = false;
                //                    label4.Text = "Usuário original";

            }


            //      label4.Text = Sanchez.Patcher.Properties.Settings.Default.FirstRun.ToString();
        }

        private void groupBox2_Enter(object sender, EventArgs e)
        {
        }

        private void Launcher_VisibleChanged(object sender, EventArgs e)
        {

        }

        private void label4_TextChanged(object sender, EventArgs e)
        {
        }

        private void button3_Click(object sender, EventArgs e)
        {

        }

        private void Launcher_Validating(object sender, CancelEventArgs e)
        {

        }

        private void Launcher_Activated(object sender, EventArgs e)
        {

        }
      
        private void button2_Click(object sender, EventArgs e)
        {
            Sanchez.Patcher.Properties.Settings.Default.nickname = textBox3.Text;
            Sanchez.Patcher.Properties.Settings.Default.Save();
          
        }

        private void Launcher_FormClosed(object sender, FormClosedEventArgs e)
        {
            Application.ExitThread();

        }

        private void Launcher_Enter(object sender, EventArgs e)
        {

        }

        private void timer1_Tick(object sender, EventArgs e)
        {



            if (Sanchez.Patcher.Properties.Settings.Default.Conta == false)
            {


                groupBox1.Visible = false;
                groupBox2.Visible = true;
                nomeToolStripMenuItem.Visible = true;

                label4.Text = "Nickname: " + Sanchez.Patcher.Properties.Settings.Default.nickname + " , Jogando com MB: " + Sanchez.Patcher.Properties.Settings.Default.memoria;
            }
            else
            {
                //    TestTimer Timer = new TestTimer();

                groupBox2.Visible = false;
                groupBox1.Visible = true;
                nomeToolStripMenuItem.Visible = false;
             
              
                label4.Text = "Jogando com MB: " + Sanchez.Patcher.Properties.Settings.Default.memoria; ;


                

            }
        }

        private void button3_Click_1(object sender, EventArgs e)
        {


        }

        private void checkBox1_CheckedChanged(object sender, EventArgs e)
        {
            if (checkBox1.Checked == true)
            {

                Sanchez.Patcher.Properties.Settings.Default.windowmode = true;
                Sanchez.Patcher.Properties.Settings.Default.Save();

            }
            else
            {
                Sanchez.Patcher.Properties.Settings.Default.windowmode = false;
                Sanchez.Patcher.Properties.Settings.Default.Save();
            }

        }

        private void checkBox2_CheckedChanged(object sender, EventArgs e)
        {





        }

        private void groupBox1_Enter(object sender, EventArgs e)
        {

        }

        private void groupBox1_Leave(object sender, EventArgs e)
        {


        }

        private void groupBox2_Leave(object sender, EventArgs e)
        {

        }

        private void textBox3_KeyDown(object sender, KeyEventArgs e)
        {

        }

        private void button3_Click_2(object sender, EventArgs e)
        {
           
        }

        private void button4_Click(object sender, EventArgs e)
        {

        }

        public void button4_Click_1(object sender, EventArgs e)
        {






        }

        private void button5_Click(object sender, EventArgs e)
        {























        }

        private void button6_Click(object sender, EventArgs e)
        {

        }

        private void button7_Click(object sender, EventArgs e)
        {








        }
        private void DownloadGame(MProfile profile, bool downloadResource = true)
        {
            MDownloader downloader = new MDownloader(profile);
            downloader.ChangeFileProgressEvent += Launcher_ChangeDownloadFileEvent;
            downloader.ChangeProgressEvent += Launcher_ChangeProgressEvent;
            downloader.DownloadAll(downloadResource);
        }

        private void Launcher_ChangeProgressEvent(ChangeProgressEventArgs e)
        {
            Invoke((MethodInvoker)delegate
            {
                toolStripStatusLabel1.Text = e.FileName;
                toolStripProgressBar1.Maximum = e.MaxValue;
                toolStripProgressBar1.Value = e.CurrentValue;
            });
        }
        private void invoker(string title, int max, int min) //스레드에서 상태표시
        {
            invoker($"{title} - {min}/{max}");
        }

        private void invoker(string msg) //스레드에서 상태표시
        {
            Invoke((MethodInvoker)delegate
            {
                toolStripStatusLabel1.Text = msg;
            });
        }
        private void Launcher_ChangeDownloadFileEvent(object sender, System.Net.DownloadProgressChangedEventArgs e)
        {
            Invoke((MethodInvoker)delegate
            {
                //toolStripProgressBar2.Value = e.ProgressPercentage;
            });
        }

        private void button3_Click_3(object sender, EventArgs e)
        {
     
        }

        private void menuStrip1_ItemClicked(object sender, ToolStripItemClickedEventArgs e)
        {

        }

        private void button3_Click_4(object sender, EventArgs e)
        {
     
        }

        private void button3_Click_5(object sender, EventArgs e)
        {
  
        }

        private void backgroundWorker1_DoWork(object sender, DoWorkEventArgs e)
        { 
            


        }

        private void button3_Click_6(object sender, EventArgs e)
             
        {



        }

        private void button3_Click_7(object sender, EventArgs e)
        {
            versions = MProfileInfo.GetProfilesFromLocal();
            comboBox1.Items.Clear();
            foreach (var item in versions)
            {
                comboBox1.Items.Add(item.Name);
            }
        }
    }
}`

**Comment by brutalzinn** [comment]
My code is here: `using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Windows.Forms;

using System.IO;
using CmlLib.Launcher;
using Sanchez.Patcher.Source_files;
using System.Threading;

namespace Sanchez.Patcher.Forms
{
    public partial class launcher : Form
    {
        public launcher()
        {
            InitializeComponent();
            Globals.Launcher = this;
            bool iswindowmode = false;


        }
        MProfileInfo[] versions;
        MSession session;
   MProfile profile = null;

        private void button1_Click(object sender, EventArgs e)
        {

        

         

            if (File.Exists(Sanchez.Patcher.Properties.Settings.Default.javapath)) {
            
               

                session = MSession.GetOfflineSession(textBox3.Text);






                string nn = Globals.versãodominecraft;
            string jj = Sanchez.Patcher.Properties.Settings.Default.javapath;

                string ln = "";
            string server = Globals.ipdoserver;

            var th = new Thread(new ThreadStart(delegate
            {



               
                MProfile forgeProfile = null;

                foreach (var item in versions)
                {
                    if (item.Name == nn)
                    {
                        profile = MProfile.Parse(item);
                        break;
                    }
                }

                if (profile.IsForge)
                {
                    foreach (var item in versions)
                    {
                        if (item.Name == profile.InnerJarId)
                        {
                            forgeProfile = MProfile.Parse(item);
                            break;
                        }
                    }

                    DownloadGame(forgeProfile, true);
                }

                DownloadGame(profile, !profile.IsForge);

                MLaunchOption option = new MLaunchOption()
                {
                    BaseProfile = forgeProfile,
                    StartProfile = profile,
                    JavaPath = jj,
                    LauncherName = ln,
                    MaximumRamMb = 500,// Sanchez.Patcher.Properties.Settings.Default.memoria,
                    ServerIp = server,
                    Session = session,
                    CustomJavaParameter = Sanchez.Patcher.Properties.Settings.Default.javaargument
                };

                if (Sanchez.Patcher.Properties.Settings.Default.largura != "" && Sanchez.Patcher.Properties.Settings.Default.altura != "")
                {
                    option.ScreenHeight = int.Parse(Sanchez.Patcher.Properties.Settings.Default.altura);
                    option.ScreenWidth = int.Parse(Sanchez.Patcher.Properties.Settings.Default.largura);
                }

                MLaunch launch = new MLaunch(option);
                var pro = launch.GetProcess(); // 인수 생성 후 설정된 Process 객체 가져옴
                System.IO.File.WriteAllText("mcarg.txt", pro.StartInfo.Arguments); // 만들어진 인수 파일로 저장 (디버그용)
                pro.Start(); // Process 객체로 실행

                this.Invoke((MethodInvoker)delegate
                {

                });
            }));
            th.Start();





            }
            else
            {

                timer1.Enabled = false;
                MessageBox.Show("Diretório java não encontrado. Por favor configure-o corretamente.  Está com dúvidas? \r\n consulte a equipe do survivalcrafters. ");


            }


        }

        private void usoDaMemóriaToolStripMenuItem_Click(object sender, EventArgs e)
        {

        }

        private void editorDeMemóriaToolStripMenuItem_Click(object sender, EventArgs e)
        {



            Patcher.Forms.configurarmemoria f2 = new Patcher.Forms.configurarmemoria();
            f2.ShowDialog();
        }

        private void nomeToolStripMenuItem_Click(object sender, EventArgs e)
        {
            //   Patcher.Forms.editordeconta f2 = new Patcher.Forms.editordeconta();
            //  f2.ShowDialog();
        }

        private void Launcher_Load(object sender, EventArgs e)
        {


            MSession session = null;


            //            Txt_Java.Text = Minecraft.mPath + "\\runtime\\bin\\javaw.exe";
        }

        private void tipoDeContaToolStripMenuItem_Click(object sender, EventArgs e)
        {

        }

        private void mudarTipoDeContaToolStripMenuItem_Click(object sender, EventArgs e)
        {
            Patcher.Forms.Formulario f2 = new Patcher.Forms.Formulario();
            f2.ShowDialog();
        }
    
        private void Launcher_Shown(object sender, EventArgs e)
        {
            Minecraft.init(Sanchez.Patcher.Properties.Settings.Default.minecraftlocal);


            versions = MProfileInfo.GetProfiles();
            Invoke((MethodInvoker)delegate
            {
                foreach (var item in versions)
                {
                    comboBox1.Items.Add(item.Name);
                }
            });
            webBrowser1.Url = new Uri( Globals.sitedobrowser);

       //     label5.Text = Sanchez.Patcher.Properties.Settings.Default.Conta.ToString();
           // string minecraft = Environment.GetEnvironmentVariable("appdata") + "\\survivalcrafters";
      //
          //  Sanchez.Patcher.Properties.Settings.Default.minecraftlocal = minecraft;
          //  Sanchez.Patcher.Properties.Settings.Default.Save();


       //     label5.Text = minecraft;

            versions = MProfileInfo.GetProfiles();



            var th = new Thread(new ThreadStart(delegate
            {
              

                versions = MProfileInfo.GetProfiles();
                //      Invoke((MethodInvoker)delegate
                //      {
                //   foreach (var item in versions)
                {
                    //       //       //Cb_Version.Items.Add(item.Name);
                    //          }
                    //      });
                    if (checkBox2.Checked == true)
                    {





                        var login = new MLogin();
                        MSession result = login.TryAutoLogin();

                        if (result.Result != MLoginResult.Success)
                            return;

                        MessageBox.Show("Auto Login foi um sucesso!");
                        session = result;
                    }
                    Invoke((MethodInvoker)delegate { button1.Enabled = true; });
                } }));
            th.Start();

   //         Minecraft.init(Environment.GetEnvironmentVariable("appdata") + "\\.minecraft");
            checkBox1.Checked = Sanchez.Patcher.Properties.Settings.Default.windowmode;
            checkBox2.Checked = Sanchez.Patcher.Properties.Settings.Default.passwordsave;

            if (checkBox2.Checked == true)
            {
                //   textBox1.Text = Sanchez.Patcher.Properties.Settings.Default.email;
                //   textBox2.Text = Sanchez.Patcher.Properties.Settings.Default.senha;
                Console.WriteLine("chegoou aqui");

            }






            timer1.Enabled = true;



            // Sanchez.Patcher.Properties.Settings.Default.email = "";
            //   Sanchez.Patcher.Properties.Settings.Default.senha = "";



            if (Sanchez.Patcher.Properties.Settings.Default.Conta == false)
            {

                groupBox1.Visible = false;
                groupBox2.Visible = true;
                nomeToolStripMenuItem.Visible = true;
                textBox3.Text = Sanchez.Patcher.Properties.Settings.Default.nickname;
                // label4.Text = "Usuário crackeado";

            }
            else
            {
                groupBox2.Visible = false;
                groupBox1.Visible = true;
                nomeToolStripMenuItem.Visible = false;
                //                    label4.Text = "Usuário original";

            }


            //      label4.Text = Sanchez.Patcher.Properties.Settings.Default.FirstRun.ToString();
        }

        private void groupBox2_Enter(object sender, EventArgs e)
        {
        }

        private void Launcher_VisibleChanged(object sender, EventArgs e)
        {

        }

        private void label4_TextChanged(object sender, EventArgs e)
        {
        }

        private void button3_Click(object sender, EventArgs e)
        {

        }

        private void Launcher_Validating(object sender, CancelEventArgs e)
        {

        }

        private void Launcher_Activated(object sender, EventArgs e)
        {

        }
      
        private void button2_Click(object sender, EventArgs e)
        {
            Sanchez.Patcher.Properties.Settings.Default.nickname = textBox3.Text;
            Sanchez.Patcher.Properties.Settings.Default.Save();
          
        }

        private void Launcher_FormClosed(object sender, FormClosedEventArgs e)
        {
            Application.ExitThread();

        }

        private void Launcher_Enter(object sender, EventArgs e)
        {

        }

        private void timer1_Tick(object sender, EventArgs e)
        {



            if (Sanchez.Patcher.Properties.Settings.Default.Conta == false)
            {


                groupBox1.Visible = false;
                groupBox2.Visible = true;
                nomeToolStripMenuItem.Visible = true;

                label4.Text = "Nickname: " + Sanchez.Patcher.Properties.Settings.Default.nickname + " , Jogando com MB: " + Sanchez.Patcher.Properties.Settings.Default.memoria;
            }
            else
            {
                //    TestTimer Timer = new TestTimer();

                groupBox2.Visible = false;
                groupBox1.Visible = true;
                nomeToolStripMenuItem.Visible = false;
             
              
                label4.Text = "Jogando com MB: " + Sanchez.Patcher.Properties.Settings.Default.memoria; ;


                

            }
        }

        private void button3_Click_1(object sender, EventArgs e)
        {


        }

        private void checkBox1_CheckedChanged(object sender, EventArgs e)
        {
            if (checkBox1.Checked == true)
            {

                Sanchez.Patcher.Properties.Settings.Default.windowmode = true;
                Sanchez.Patcher.Properties.Settings.Default.Save();

            }
            else
            {
                Sanchez.Patcher.Properties.Settings.Default.windowmode = false;
                Sanchez.Patcher.Properties.Settings.Default.Save();
            }

        }

        private void checkBox2_CheckedChanged(object sender, EventArgs e)
        {





        }

        private void groupBox1_Enter(object sender, EventArgs e)
        {

        }

        private void groupBox1_Leave(object sender, EventArgs e)
        {


        }

        private void groupBox2_Leave(object sender, EventArgs e)
        {

        }

        private void textBox3_KeyDown(object sender, KeyEventArgs e)
        {

        }

        private void button3_Click_2(object sender, EventArgs e)
        {
           
        }

        private void button4_Click(object sender, EventArgs e)
        {

        }

        public void button4_Click_1(object sender, EventArgs e)
        {






        }

        private void button5_Click(object sender, EventArgs e)
        {























        }

        private void button6_Click(object sender, EventArgs e)
        {

        }

        private void button7_Click(object sender, EventArgs e)
        {








        }
        private void DownloadGame(MProfile profile, bool downloadResource = true)
        {
            MDownloader downloader = new MDownloader(profile);
            downloader.ChangeFileProgressEvent += Launcher_ChangeDownloadFileEvent;
            downloader.ChangeProgressEvent += Launcher_ChangeProgressEvent;
            downloader.DownloadAll(downloadResource);
        }

        private void Launcher_ChangeProgressEvent(ChangeProgressEventArgs e)
        {
            Invoke((MethodInvoker)delegate
            {
                toolStripStatusLabel1.Text = e.FileName;
                toolStripProgressBar1.Maximum = e.MaxValue;
                toolStripProgressBar1.Value = e.CurrentValue;
            });
        }
        private void invoker(string title, int max, int min) //스레드에서 상태표시
        {
            invoker($"{title} - {min}/{max}");
        }

        private void invoker(string msg) //스레드에서 상태표시
        {
            Invoke((MethodInvoker)delegate
            {
                toolStripStatusLabel1.Text = msg;
            });
        }
        private void Launcher_ChangeDownloadFileEvent(object sender, System.Net.DownloadProgressChangedEventArgs e)
        {
            Invoke((MethodInvoker)delegate
            {
                //toolStripProgressBar2.Value = e.ProgressPercentage;
            });
        }

        private void button3_Click_3(object sender, EventArgs e)
        {
     
        }

        private void menuStrip1_ItemClicked(object sender, ToolStripItemClickedEventArgs e)
        {

        }

        private void button3_Click_4(object sender, EventArgs e)
        {
     
        }

        private void button3_Click_5(object sender, EventArgs e)
        {
  
        }

        private void backgroundWorker1_DoWork(object sender, DoWorkEventArgs e)
        { 
            


        }

        private void button3_Click_6(object sender, EventArgs e)
             
        {



        }

        private void button3_Click_7(object sender, EventArgs e)
        {
            versions = MProfileInfo.GetProfilesFromLocal();
            comboBox1.Items.Clear();
            foreach (var item in versions)
            {
                comboBox1.Items.Add(item.Name);
            }
        }
    }
}`

**Comment by AlphaBs** [comment]
you set MaximumRamMb too small.
MaximumRamMb = 500 is 0.5GB.
Mojang launcher's default setting is 1GB.
Set MaximumRamMb = 4096. (4GB)
