### ISSUE TITLE
Crash on 1.14.4

### ISSUE THREAD

**Issue by FabioZumbi12** [AlphaBs/MinecraftLauncherLibrary#4]
Hi,

Excelent sources!!

I trying to use to run for my pixelmon server and my 1.14.4 servers, but on try to run for 1.14.4 it crashes!

On 1.13.2 and lowers runs fine, its only with 1.14.4!

Maybe some jvm args have changed?

**Comment by AlphaBs** [comment]
maybe... i will check it and fix code

**Comment by AlphaBs** [comment]
fix it. but this version isn't stable

**Comment by FabioZumbi12** [comment]
Cool, thanks! 
Btw, i am using from NuGet, can you update the nuget package?
It still on 0.0.5

Edit: or build a .dll with this latest changes

**Comment by AlphaBs** [comment]
okay i will do that tomorrow

**Comment by AlphaBs** [comment]
0.0.6 was released

**Comment by FabioZumbi12** [comment]
Excelent work man, thanks!! It worked 100%!
