### ISSUE TITLE
라이선스 질문이요

### ISSUE THREAD

**Issue by ilsubyeega** [AlphaBs/MinecraftLauncherLibrary#8]
![image](https://user-images.githubusercontent.com/37479424/71782635-c1b1dd00-301f-11ea-8017-496c3f7d0f5b.png)
[이 주소](https://creativecommons.org/licenses/by/4.0/deed.ko)에 따르면 영리 목적으로 이용된다고 하는데, 혹시 상업 목적으로도 가능한건가요? (아직 준비는 안했다만 다른 프로젝트에 사용할 생각이 있습니다)

**Comment by AlphaBs** [comment]
네. 1.0.0버전부터는 출처 표기만 한다면 어떠한 방식으로도 소스 코드를 이용할 수 있습니다.

**Comment by ilsubyeega** [comment]
확인했습니다.
그런데 MIT도 괜찮다고 봅니다. 이슈를 닫겠습니다.
