### ISSUE TITLE
how i can add server to serverlist?

### ISSUE THREAD

**Issue by karlovm** [AlphaBs/MinecraftLauncherLibrary#9]
Very good! Thanks for it! I really enjoy your library
But how i can add server to serverlist automatically?

**Comment by AlphaBs** [comment]
there is no such function in CmlLib, but you can make it through [fNBT](https://github.com/mstefarov/fNbt)
and check [servers.dat format](https://minecraft.gamepedia.com/Servers.dat_format)

**Comment by karlovm** [comment]
Can I wait for update with this good function?

**Comment by AlphaBs** [comment]
sorry, I don't have any plan to add that function
